sonar.projectKey=spanesso_android-fake-store-app
sonar.organization=spanesso
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/build/**,**/*.json,**/generated/**,**/res/**,**/.gradle/**

sonar.java.source=17
sonar.kotlin.file.suffixes=.kt,.kts
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

# Kover (Kotlin coverage) genera el XML en esta ruta por flavor
sonar.coverage.jacoco.xmlReportPaths=**/build/reports/kover/report.xml,**/build/reports/kover/xml/report.xml

# Binarios compilados (necesarios para análisis de bytecode)
sonar.java.binaries=**/build/intermediates/javac/**,**/build/tmp/kotlin-classes/**
